### ISSUE TITLE
Can not login with admin@admin.com and foobar

### ISSUE THREAD

**Issue by BruceHan98** [blackcandy-org/blackcandy#271]
I deploy black candy with docker-compose up, but can not login with admin@admin.com and foobar. I don't know where the problem is.

**Comment by aidewoode** [comment]
What is version of Black Candy that you deployed? And also please post content of your `docker-compose.yml` file.

**Comment by BruceHan98** [comment]
I just use the following `docker-compose.yml` to deploy black candy:
```yaml
version: '3.4'
services:
  app: &app_base
    container_name: 'blackcandy_app'
    image: blackcandy/blackcandy
    volumes:
      - ./log:/app/log
      - /media_data:/media_data
      - production_uploads_data:/app/public/uploads
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      REDIS_CACHE_URL: redis://redis:6379/1
      REDIS_SIDEKIQ_URL: redis://redis:6379/2
      MEDIA_PATH: /media_data
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: 'blackcandy_postgres'
    image: postgres:11.1-alpine
    volumes:
      - production_db_data:/var/lib/postgresql/data
  redis:
    container_name: 'blackcandy_redis'
    image: redis:4.0-alpine
    volumes:
      - production_redis_data:/data
  worker:
    container_name: 'blackcandy_worker'
    <<: *app_base
    command: bundle exec sidekiq
  web:
    container_name: 'blackcandy_web'
    <<: *app_base
    depends_on:
      - app
      - worker
    ports:
      - 8000:80
    command: nginx -g 'pid /tmp/nginx.pid; daemon off;'
volumes:
  production_db_data:
  production_redis_data:
  production_uploads_data:
```
