### ISSUE TITLE
Using persist mount (/app/storage) causes errors on start

### ISSUE THREAD

**Issue by GhostDog98** [blackcandy-org/blackcandy#403]
When using the docker compose file of:
```
version: '3.8'

services:
  blackcandy:
    image: ghcr.io/blackcandy-org/blackcandy:latest
    container_name: blackcandy
    volumes:
      - /media_data:/media_data
    environment:
      - MEDIA_PATH=/media_data
      - SECRET_KEY_BASE=<data>
    ports:
      - "3000:3000"
    restart: unless-stopped
 ```
 
 The service launches fine. However, when attempting to set the persist data mount (see below), it doesn't launch due to not seeing any database files in said persist mount:
 ```
  ✔ Container blackcandy  Created                                                                                                                               0.0s 
Attaching to blackcandy
blackcandy  | bin/rails aborted!
blackcandy  | ActiveRecord::StatementInvalid: SQLite3::CantOpenException: unable to open database file (ActiveRecord::StatementInvalid)
blackcandy  | 
blackcandy  | 
blackcandy  | Caused by:
blackcandy  | SQLite3::CantOpenException: unable to open database file (SQLite3::CantOpenException)
blackcandy  | 
blackcandy  | Tasks: TOP => db:prepare
blackcandy  | (See full trace by running task with --trace)
blackcandy  | [16] Puma starting in cluster mode...
blackcandy  | [16] * Puma version: 6.4.2 (ruby 3.3.1-p55) ("The Eagle of Durango")
blackcandy  | [16] *  Min threads: 5
blackcandy  | [16] *  Max threads: 5
blackcandy  | [16] *  Environment: production
blackcandy  | [16] *   Master PID: 16
blackcandy  | [16] *      Workers: 4
blackcandy  | [16] *     Restarts: (✔) hot (✖) phased
blackcandy  | [16] * Preloading application
blackcandy  | [16] * Listening on http://0.0.0.0:3000
```

Said docker compose file that generates this error:
```
version: '3.8'

services:
  blackcandy:
    image: ghcr.io/blackcandy-org/blackcandy:latest
    container_name: blackcandy
    volumes:
      - /media_data:/media_data
      - ./storage_data:/app/storage
    environment:
      - MEDIA_PATH=/media_data
      - SECRET_KEY_BASE=<data>
    ports:
      - "3000:3000"
    restart: unless-stopped
``` 
Is there a step I'm missing here?
